spring:
  datasource:
    url: jdbc:h2:mem:insurance_db
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  fraud-analysis:
    base-url: http://localhost:8089

logging:
  level:
    br.com.itau: DEBUG
    org.hibernate.SQL: DEBUG